### ISSUE TITLE
coolbpf vs btfhub+btfgen

### ISSUE THREAD

**Issue by nevermosby** [aliyun/coolbpf#10]
I think `coolbpf` is a cool combination of btfhub and btfgen. 

Could u list some other advantages over btfhub and btfgen?

**Comment by wenamao** [comment]
Do you mean btfhub and btfgen? Both btfhub and btfgen is only to generate btf and try to compress it, coolbpf generate BTF automatically as soon as new main distribute kernel version deliver, and it also compress it and publish on http://pylcc.openanolis.cn.

**Comment by nevermosby** [comment]
Gotcha
