### ISSUE TITLE
golcc make异常

### ISSUE THREAD

**Issue by zhuanshenlikai** [aliyun/coolbpf#14]
在lcc/golcc/rexample/hello下面执行`make`，出现了以下异常：
![1667806811499](https://user-images.githubusercontent.com/12570095/200252905-81c9a930-38c3-4365-8176-5c90371dfe0b.jpg)
是下载的libbpfgo的版本问题么，我应当怎样解决？

**Comment by chentao-kernel** [comment]
libbpf库版本落后libbpfgo了，需要更新下libbpf，更新方法见：https://gitee.com/anolis/coolbpf
https://gitee.com/anolis/coolbpf/tree/master/lcc/golcc

**Comment by zhuanshenlikai** [comment]
> libbpf库版本落后libbpfgo了，需要更新下libbpf，更新方法见：https://gitee.com/anolis/coolbpf https://gitee.com/anolis/coolbpf/tree/master/lcc/golcc
