### ISSUE TITLE
 【Anolis OS 8.6 ANCK 64位 ARM版】 运行hello.py 编译错误

### ISSUE THREAD

**Issue by su-cheng** [aliyun/coolbpf#17]
1.在龙蜥实验室申请了一台【Anolis OS 8.6 ANCK 64位 ARM版】机器，并按照coolbpf_handbook.md安装好了coolbpf运行环境：
![image](https://user-images.githubusercontent.com/112916389/209950865-abfb5fae-a9c7-4154-9be2-82066c847d5a.png)
![image](https://user-images.githubusercontent.com/112916389/209950523-624e0d69-2327-4a93-b852-5c407a733dc0.png)

2.在运行hello.py时，出现如下编译错误：
![image](https://user-images.githubusercontent.com/112916389/209950799-389f3ba8-a226-4cb6-aa8c-519b13d14d7c.png)

**Comment by wenamao** [comment]
抱歉，目前远端编译服务器暂不支持ARM。
