### ISSUE TITLE
编译make ebpfdrv KERNEL_VERSION=3.10.0-514.26.2.el7.x86_64报错

### ISSUE THREAD

**Issue by oupeng007** [aliyun/coolbpf#23]
ome/coolbpf/build/lcc/glcc/lib/ebpf/bpf_trace.c:682:11: error: ‘bpf_get_stackid_proto_tp’ undeclared (first use in this function)
   return &bpf_get_stackid_proto_tp;

请问这个什么原因怎么解决

**Comment by xsj0jsx** [comment]
把这1行注释了就行了。
