### ISSUE TITLE
请教一下bpf关于拼接长字符串的问题，

### ISSUE THREAD

**Issue by Killing11L** [aliyun/coolbpf#26]
您好，麻烦请教一下就是我在内核态程序需要循环通过struct dentry结构获取某一个文件的路径，我的方法目前是首先有一个结构体，结构体内部有一个`char filename[512];`的数组，然后循环将每一级目录加上'/'拼成一个完整的路径，
问题是循环过程中调用`bpf_probe_read_kernel_str`接口向`filename`中拷贝时如果第二个参数是一个变量，那么运行时Bpf校验器就会说可能越界什么的，但是在前后我已经做了很完善的边界检查了，之所以`bpf_probe_read_kernel_str`第二个参数需要是变量是因为每一级目录名长度是不同的，当我改成一个定值就没问题了。
其实总的来说就是bpf如何拼接一个长字符串，我基本尝试过所有相关的接口也无法解决了
下面是部分代码

其中用到的部分定义如下
```c
char filename[512];
#define MAX_DENTRY_NAME_LEN         20
```

```c
    size_t pos = 0;
    const u32 MAX_BACKTRACE_DEPTH = 20;
    for (u32 cnt = MAX_BACKTRACE_DEPTH; cnt != 0; --cnt) {
        if (err || curr_dentry == NULL) {
            break;
        }
        int name_len = BPF_CORE_READ(curr_dentry, d_name.len);
        const u8 *name = BPF_CORE_READ(curr_dentry, d_name.name);
        if (name_len <= 1) {
            break;
        }
        name_len = bpf_probe_read_kernel_str(filename + pos, MAX_DENTRY_NAME_LEN, name);
        if (name_len <= 1) {
            BPFLOGD(BPF_TRUE, "failed to read dentry name from kernel stack buffer");
            break;
        }
        pos += name_len;
        filename[pos - 1] = '/';
        struct dentry *temp_dentry = BPF_CORE_READ(curr_dentry, d_parent);
        if (temp_dentry == curr_dentry || temp_dentry == NULL) {
            break;
        }
        curr_dentry = temp_dentry;
    }
```
目前的效果是只能去循环20层，每层目录拿20个字符，我也将`filename`改为了4096长度，但是`bpf_probe_read_kernel_str`接口还是不允许我使用变量（上面代码中的`name_len`）作为第二个参数，我最终想要的效果其实是想通过循环可以完整的拿到每一级目录名，以及最终拼接成完整的路径，请教大佬是否有好的解决方案，感谢！！！

**Comment by guomsh** [comment]
据我所知，eBPF 堆栈大小被限制在 MAX_BPF_STACK，现在应该是512字节，你这样用应该是越界的，解决方法是改用 bpf maps存储。

/* BPF program can access up to 512 bytes of stack space. */
#define MAX_BPF_STACK   512

**Comment by Killing11L** [comment]
> 据我所知，eBPF 堆栈大小被限制在 MAX_BPF_STACK，现在应该是512字节，你这样用应该是越界的，解决方法是改用 bpf maps存储。
> 
> /* BPF program can access up to 512 bytes of stack space. */ #define MAX_BPF_STACK 512

ok，我尝试一些，非常感谢

**Comment by majoki** [comment]
老哥，请问解决了吗，我最近也想构建完整的路径

**Comment by Killing11L** [comment]
> 老哥，请问解决了吗，我最近也想构建完整的路径

并没有好的解决办法吧

**Comment by luxingwen** [comment]
最近在做这个东西，我已经解决，并且兼容3.10内核的操作系统。不过我用的是libbpf，没有使用coolbpf， coolbpf 还没玩过。

**Comment by Killing11L** [comment]
> 最近在做这个东西，我已经解决，并且兼容3.10内核的操作系统。不过我用的是libbpf，没有使用coolbpf， coolbpf 还没玩过。

请教一下你是大概怎么处理的呢
